### ISSUE TITLE
CatBoost support

### ISSUE THREAD

**Issue by iFe1er** [kaz-Anova/StackNet#46]
CatBoost (https://tech.yandex.com/catboost/) is a very powerful LGBM tools for machine learning.  

I hope someone can add this tool to the StackNet.

**Comment by goldentom42** [comment]
Hi there,
I believe you can use CatBoost in StackNet provided it's installed in your python environment.
You can then call CatBoost inside [python generic model](https://github.com/kaz-Anova/StackNet#install-python-generic-algorithmsnew) .
Also you can have a look at issue #40 for further info.
Hope this helps.

**Comment by kaz-Anova** [comment]
@iFe1er  I am aware of the tool and I like it. However the way StackNet is structured , it expects an algorithm to be be able to support sparse and dense representation of the data. CatBooost currently supports only dense data](https://github.com/catboost/catboost/issues/1) . 

I will officially add it when this changes. Otherwise as @goldentom42 suggested, you can run it using the python generic model.

**Comment by iFe1er** [comment]
@kaz-Anova  @goldentom42  Thank you guys for the quick and professional reply! I will try python generic model. Closing the issue now. THANKS AGAIN!
